//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by rlToday.rc
//
#define IDD_DIALOG_TZ_EDIT              102
#define IDD_DIALOG_DATE                 106
#define IDD_DIALOG_USER                 107
#define IDD_DIALOG_GENERAL              108
#define IDD_DIALOG_CAL2                 109
#define IDD_DIALOG_CLOCK                111
#define IDI_ICON1                       114
#define IDR_CONTEXT_MENU                115
#define IDD_DIALOG_BACKGROUND           116
#define IDD_DIALOG_ABOUT                117
#define IDD_DIALOG_TIMEZONES            118
#define IDD_DIALOG_CALENDAR             120
#define IDD_DIALOG_EDIT                 122
#define IDI_ICON_NON                    123
#define IDD_DIALOG_SELECTFILE           124
#define IDD_DIALOG_SELECTDIRECTORY      143
#define IDD_DIALOG_CAL                  501
#define IDD_DIALOG_APPS                 501
#define IDC_CHECK_SHOW_CLOCK            1000
#define IDC_EDIT_X                      1001
#define IDC_EDIT_Y                      1002
#define IDC_EDIT_FONTSIZE               1003
#define IDC_BUTTON_COLOR                1004
#define IDC_EDIT_MAXSIZE                1005
#define IDC_EDIT_BMP                    1006
#define IDC_BUTTON_BMP                  1007
#define IDC_CHECK_SHOW                  1008
#define IDC_BUTTON_UNINSTALL            1009
#define IDC_EDIT_DATEFORMAT             1009
#define IDC_EDIT_RASTER_X               1009
#define IDC_EDIT_RASTER_Y               1010
#define IDC_EDIT_BMP_SU                 1010
#define IDC_BUTTON_COLOR_TD             1011
#define IDC_RADIO_BACKG1                1011
#define IDC_RADIO_BACKG2                1012
#define IDC_BUTTON_COLOR_WD             1013
#define IDC_RADIO_BACKG3                1013
#define IDC_BUTTON_COLOR_SA             1014
#define IDC_EDIT_PATH                   1014
#define IDC_BUTTON_COLOR_SU             1015
#define IDC_BUTTON_GRAPHIC_TD           1016
#define IDC_RADIO_AUTO1                 1016
#define IDC_BUTTON_GRAPHIC_WD           1017
#define IDC_RADIO_AUTO2                 1017
#define IDC_BUTTON_GRAPHIC_SA           1018
#define IDC_EDIT_HEIGHT                 1018
#define IDC_BUTTON_GRAPHIC_SU           1019
#define IDC_PREVIEW                     1019
#define IDC_EDIT_BMP_TD                 1020
#define IDC_SPIN1                       1020
#define IDC_SPIN_POS_X                  1020
#define IDC_SPIN_HEIGHT                 1020
#define IDC_EDIT_BMP_WD                 1021
#define IDC_SPIN_POS_Y                  1021
#define IDC_EDIT_BMP_SA                 1022
#define IDC_TAB                         1022
#define IDC_SPIN_FONT_SIZE              1022
#define IDC_SPIN_RASTER_X               1023
#define IDC_SPIN_MAX_WIDTH              1023
#define IDC_SPIN_RASTER_Y               1024
#define IDC_BUTTON_COLOR_CLOCK          1025
#define IDC_MONTHCALENDAR1              1025
#define IDC_BUTTON_GRAPHIC_CLOCK        1026
#define IDC_COMBO_SKIN                  1026
#define IDC_BUTTON_COLOR_DATE           1027
#define IDC_BUTTON_GRAPHIC_DATE         1028
#define IDC_LIST_SKIN                   1029
#define IDC_LIST_TIMEZONES              1031
#define IDC_BUTTON_ADD                  1032
#define IDC_BUTTON_ADD2                 1033
#define IDC_LIST_TIMEZONES2             1034
#define IDC_LIST_APPLICATIONS           1034
#define IDC_LIST_FILE                   1034
#define IDC_BUTTON_EDIT                 1037
#define IDC_BUTTON_UP                   1038
#define IDC_BUTTON_DELETE               1039
#define IDC_BUTTON_DOWN                 1040
#define IDC_BUTTON_EDIT2                1041
#define IDC_BUTTON_DELETE2              1042
#define IDC_BUTTON_UP2                  1043
#define IDC_BUTTON_DOWN2                1044
#define IDC_EDIT_TZ_NAME                1050
#define IDC_COMBO_TZ                    1051
#define IDC_COMBO_WEEKDAY               1053
#define IDC_EDIT_SU                     1054
#define IDC_EDIT_MO                     1055
#define IDC_EDIT_TU                     1056
#define IDC_EDIT_NAME                   1056
#define IDC_EDIT_WE                     1057
#define IDC_BUTTON_FILESELECT           1057
#define IDC_EDIT_CMD                    1058
#define IDC_BUTTON_CMDSELECT            1059
#define IDC_EDIT_ICO                    1060
#define IDC_EDIT_TH                     1061
#define IDC_BUTTON_ICOSELECT            1061
#define IDC_EDIT_FR                     1062
#define IDC_EDIT7                       1063
#define IDC_EDIT_SA                     1063
#define IDC_COMBO_PATH                  1064
#define IDC_STATIC_FILE                 1079
#define MNU_OPTIONS                     40001
#define IDS_CAP_OPTIONEN                40003
#define MNU_RELOADSKIN                  40005
// Next default values for new objects
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40006
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
